cripts:
  - name: Install Flutter dependencies
    script: |
      flutter pub get
      cd ios
      pod install
      cd ..

  - name: Build iOS .ipa
    script: |
      flutter build ios --release --no-codesign