name: register_app2
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  pin_code_fields: ^8.0.1
  google_fonts: ^6.2.1
  cloud_functions: ^5.3.2
  cloud_firestore: ^5.6.6
  get: ^4.1.4
  firebase_dynamic_links: ^6.1.2   # إضافة الحزمة هنا
  crypt: ^4.2.1
  shared_preferences: ^2.2.2
  intl_phone_field: ^3.1.0
  email_validator: ^2.1.17
  badges: ^3.0.2





dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/icons8-home-50.png 
    - images/icons8-email-30.png
    - images/icons8-password-50.png
    - images/icons8-phone-50.png
    - images/icons8-user-50.png
    - images/icons8-back-50.png
    - images/icons8-password-64.png
    - images/icons8-submit-progress-50.png
    - images/pool.jpg
    - images/icons8-add-50.png
    - images/icons8-location-50.png
    - images/icons8-rename-32.png
    - images/icons8-gym-50.png
    - images/icons8-measure-50.png
    - images/icons8-surface-50.png
    - images/first.jpg
    - images/LOG.png
    - images/for.png
    - images/register2.png
    - images/cha.png





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package