name: register_app2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  pin_code_fields: ^8.0.1
  google_fonts: ^5.1.0 
  cloud_functions: ^5.3.2
  cloud_firestore: ^5.6.3
  get: ^4.1.4
  firebase_dynamic_links: ^6.1.2
  crypt: ^4.2.1
  shared_preferences: ^2.2.2
  intl_phone_field: ^3.1.0
  email_validator: ^2.1.17
  badges: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/icons8-home-50.png 
    - images/icons8-email-30.png
    - images/icons8-password-50.png
    - images/icons8-phone-50.png
    - images/icons8-user-50.png
    - images/icons8-back-50.png
    - images/icons8-password-64.png
    - images/icons8-submit-progress-50.png
    - images/pool.jpg
    - images/icons8-add-50.png
    - images/icons8-location-50.png
    - images/icons8-rename-32.png
    - images/icons8-gym-50.png
    - images/icons8-measure-50.png
    - images/icons8-surface-50.png
    - images/first.jpg
    - images/LOG.png
    - images/for.png
    - images/register2.png
    - images/cha.png