// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOBSAuyUfEX-8noHpFySagjmzl_mrw0SQ',
    appId: '1:1055708963499:web:8541dee2cb6420a2b74dee',
    messagingSenderId: '1055708963499',
    projectId: 'pool-13fd0',
    authDomain: 'pool-13fd0.firebaseapp.com',
    storageBucket: 'pool-13fd0.firebasestorage.app',
    measurementId: 'G-936JR54FEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1KjODdqGupKEcgwogn4BkQobfLXsd39E',
    appId: '1:1055708963499:android:f20c42cc686ee290b74dee',
    messagingSenderId: '1055708963499',
    projectId: 'pool-13fd0',
    storageBucket: 'pool-13fd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0ZM30cNg8jKwhcPuf5MygJtlaFiPiOIQ',
    appId: '1:1055708963499:ios:37b8556d763d809bb74dee',
    messagingSenderId: '1055708963499',
    projectId: 'pool-13fd0',
    storageBucket: 'pool-13fd0.firebasestorage.app',
    iosBundleId: 'com.example.registerApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0ZM30cNg8jKwhcPuf5MygJtlaFiPiOIQ',
    appId: '1:1055708963499:ios:37b8556d763d809bb74dee',
    messagingSenderId: '1055708963499',
    projectId: 'pool-13fd0',
    storageBucket: 'pool-13fd0.firebasestorage.app',
    iosBundleId: 'com.example.registerApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOBSAuyUfEX-8noHpFySagjmzl_mrw0SQ',
    appId: '1:1055708963499:web:8a15855c0bfcc9afb74dee',
    messagingSenderId: '1055708963499',
    projectId: 'pool-13fd0',
    authDomain: 'pool-13fd0.firebaseapp.com',
    storageBucket: 'pool-13fd0.firebasestorage.app',
    measurementId: 'G-T547FG5M3K',
  );
}