install! 'cocoapods', :repo_update => true

platform :ios, '13.0'

# بقية ملف Podfile
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

end
