platform :ios, '13.0'

install! 'cocoapods'

require File.expand_path(File.join('Flutter', 'podhelper.rb'), __dir__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  install_all_flutter_pods(File.dirname(File.realpath(__FILE__)))
end
